version: "3.9"

services:
  app:
    build: ./app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/usr/src/app
    command: > 
      bash -c " python3 manage.py wait_for_db &&
                python3 manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    environment:
      - DEBUG=True
    stdin_open: true
    tty: true 

  db:
    image: postgis/postgis:14-3.2-alpine
    env_file:
      - app/envs/.env
    ports:
      - "5432:5432"
