# Generated by Django 4.1 on 2022-08-31 17:43

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('origin_location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Origin coordinates')),
                ('destination_location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Destination coordinates')),
                ('address', models.CharField(max_length=250, verbose_name='Address')),
                ('zipcode', models.CharField(max_length=100, verbose_name='Zipcode')),
                ('ext_number', models.CharField(max_length=50, verbose_name='Number')),
                ('int_number', models.CharField(max_length=50, verbose_name='Internal number')),
                ('number_products', models.IntegerField(verbose_name='Number of products')),
                ('products_size', models.CharField(choices=[('SM', 'Small. Max 5kg'), ('M', 'Medium. Max 16kg'), ('LG', 'Large. Max 25Kg')], max_length=5, verbose_name='Products size')),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('COLLECTED', 'Collected'), ('IN_STATION', 'In station'), ('ON_ROUTE', 'On route'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='CREATED', max_length=30, verbose_name='Warrant status')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
